### ISSUE TITLE
django Exceptions Middleware: inaccurate doc

### ISSUE THREAD

**Issue by fvgoto** [python-social-auth/social-docs#22]
[docs/configuration/django.rst](https://github.com/python-social-auth/social-docs/blob/master/docs/configuration/django.rst) at line 235 states:
`Exception processing is disabled if **any** of this settings is defined with a True value:`

But having `DEBUG=True` and by setting e.g. `SOCIAL_AUTH_RAISE_EXCEPTIONS = False`, it is enabled.

Relevant code point:
[social_django/middleware.py, line 56](https://github.com/python-social-auth/social-app-django/blob/master/social_django/middleware.py#L56):
  `strategy.setting('RAISE_EXCEPTIONS', settings.DEBUG)`
(If `RAISE_EXCEPTIONS` is set (even to False), it is taken.)

Documentation should reflect this.

**Comment by omab** [comment]
Fixed https://github.com/python-social-auth/social-app-django/blob/c26ae9380d01379ab794b753ce780deada71252d/social_django/middleware.py#L56
