### ISSUE TITLE
Access the domain name of the request in partial pipeline

### ISSUE THREAD

**Issue by devxpy** [python-social-auth/social-docs#29]
I need to access the domain of the request because I host on different websites from the same django server and the login behaves differently depending on which domain makes request

In django views, I can access it by  `request.META['HTTP_HOST']`
Can you please tell me the correct way to do it in a partial pipeline?

Here is my current pipeline.
I have a groupdomain model that stores the verification_methods for a domain
I want it so that if any one of the verification methods is not in the session, then the user gets redirected to enter the required details
```
@partial
def require_extra_info(strategy, user, uid, details, is_new, *args, **kwargs):
    if is_new:
        domain = models.GroupDomain.objects.get(domain=request.META['HTTP_HOST'])

        for method in domain.verification_methods:
            if strategy.session_get(method, None) is None:
                current_partial = kwargs.get('current_partial')
                # redirect him so he can provide extra info
                return redirect(urlresolvers.reverse('additional info', kwargs={'backend': current_partial.backend}))
```

**Comment by johndavidmullen** [comment]
I have the same issue, I'd like to know what domain is making the request as in "{domain}/social/login/google_oath2. Did you figure this out?
