### ISSUE TITLE
Register by access token example lints "unused variable"

### ISSUE THREAD

**Issue by aldnav** [python-social-auth/social-docs#33]
The [example](https://github.com/python-social-auth/social-docs/blob/master/docs/use_cases.rst#signup-by-oauth-access_token) lints `Local variable 'token' is assigned to but never used.` The [fix is a simple 
 param substitution](https://github.com/python-social-auth/social-docs/pull/34/files) in the `request.backend.do_auth` call.

**Comment by omab** [comment]
PR merged, thanks!
