### ISSUE TITLE
Setup pull request builds on readthedocs.org

### ISSUE THREAD

**Issue by nijel** [python-social-auth/social-docs#76]
@omab, can you please enable pull request builds on the reathedocs.org? It tests that the documentation builds and provides it for browsing making it easier to review how it will look rendered.

Documentation: https://docs.readthedocs.io/en/latest/pull-requests.html

It can be enabled in the advanced settings: https://readthedocs.org/dashboard/python-social-auth/advanced/

**Comment by omab** [comment]
@nijel, done and also added you as a maintainer in the project.

**Comment by nijel** [comment]
Hmm, it seems it did not automatically update the webhook to receive pull request events. Unfortunately, I don't have permissions on GitHub to fix this, can you please click on "Resync webhook" at https://readthedocs.org/dashboard/python-social-auth/integrations/115344/?

**Comment by omab** [comment]
@nijel, didn't look like that was needed, I confirm the builds for PRs is happening, you can see one in #77, which links to: https://python-social-auth--77.org.readthedocs.build/en/77/

**Comment by nijel** [comment]
The sync did happen, thanks: https://readthedocs.org/dashboard/python-social-auth/integrations/115344/exchange/55fa4a01-9cb6-406c-8308-c2d93d1ef7ad/
