### ISSUE TITLE
Docs are missing in action

### ISSUE THREAD

**Issue by atodorov** [python-social-auth/social-docs#85]
Opened the docs site to check something and I got this:

![Screenshot_2021-04-27 Maze Found Read the Docs](https://user-images.githubusercontent.com/1002300/116294854-1d6a2180-a7a1-11eb-94cb-ed6b983bda17.png)

**Comment by nijel** [comment]
Which URL did you open? https://python-social-auth.readthedocs.io/ works just fine for me...

**Comment by atodorov** [comment]
It was https://python-social-auth-docs.readthedocs.io !  I wasn't ware of the change but a redirect would be helpful.

**Comment by nijel** [comment]
I'm not aware of any chnage in this...
